version: '3'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    command: >
      bash -c "echo "Hello world""
    networks:
      - backend_network
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .docker/postgres
      dockerfile: Dockerfile
    container_name: postgres
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    env_file:
      - .docker/.env
    ports:
      - "5432:5432"
    networks:
      - backend_network

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    command: >
      bash -c "echo "Hello world""
    volumes:
      - frontend_volume:/app/dist
    networks:
      - frontend_network
    ports:
      - "3000:3000"

  # если по красоте выпускать сертификаты и прочее то надо будент менять .docker/nginx/nginx.conf
  nginx:
    build:
      context: .docker/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - frontend_volume:/usr/share/nginx/html
    env_file:
      - .docker/.env
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - frontend_network
      - backend_network


networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge

volumes:
  postgres_storage:
  frontend_volume: