# Generated by Django 5.0.6 on 2024-05-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number', models.CharField(max_length=10, verbose_name='Серия и номер паспорта')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('who_issued', models.CharField(max_length=50, verbose_name='Кем выдан документ')),
                ('department_code', models.CharField(max_length=7, verbose_name='Код подразделения')),
                ('dob', models.DateField(verbose_name='Дата рождения')),
                ('place_of_birth', models.CharField(max_length=25, verbose_name='Место рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Snils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_snils', models.CharField(max_length=11, verbose_name='Номер СНИЛСа')),
            ],
        ),
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('passport_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_data.passportdata', verbose_name='Паспортные данные')),
                ('snils', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person_data.snils', verbose_name='СНИЛС')),
            ],
        ),
    ]
