# Generated by Django 5.0.6 on 2024-05-25 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotarisedOfAttorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='ФИО')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания действия доверенности')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('ogrn', models.CharField(max_length=13, verbose_name='ОГРН')),
                ('kpp', models.CharField(max_length=9, verbose_name='КПП')),
                ('full_name', models.CharField(verbose_name='Полное наименование')),
                ('legal_address', models.CharField(verbose_name='Юридический адрес')),
                ('mailing_address', models.CharField(verbose_name='Почтовый адрес')),
            ],
        ),
        migrations.AddField(
            model_name='persondata',
            name='proxy_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person_data.notarisedofattorney'),
        ),
        migrations.AddField(
            model_name='persondata',
            name='org_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='person_data.organization'),
        ),
    ]
